version: 2

models:
  - name: int__session_events_agg
    description: Session event aggregated to count the number of events in each type
  - name: int__session_events_basic_agg
    description: Event type by session id and user
  - name: fct__session
    description: summary information session's event type and time spent by the user